services:
  db:
    image: postgis/postgis:18-3.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paddlemate
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: ./api
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@db:5432/paddlemate
  #     KEYCLOAK_URL: http://keycloak:8080
  #     KEYCLOAK_REALM: myrealm
  #     KEYCLOAK_AUDIENCE: account
  #     KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/myrealm/protocol/openid-connect/token
  #     KEYCLOAK_CLIENT_ID: paddlemate-api
  #     KEYCLOAK_CLIENT_SECRET: change-me
  #     PORT: 3000
  #     BASE_URL: /api/v1
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - keycloak

volumes:
  db_data:
