/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all API tokens for the authenticated user. Does not include revoked tokens. */
        get: operations["list_tokens"];
        put?: never;
        /** @description Create a new API token. The token is only shown once at creation time - store it securely! */
        post: operations["create_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Revoke an API token. The token will no longer be usable for authentication. */
        delete: operations["revoke_token"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List groups the authenticated user belongs to */
        get: operations["list_groups"];
        put?: never;
        /** @description Create a new group; the caller becomes owner */
        post: operations["create_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a group with its members (members only) */
        get: operations["get_group"];
        /** @description Update a group (owner or group admin only) */
        put: operations["update_group"];
        post?: never;
        /** @description Delete a group (owner or server admin only) */
        delete: operations["delete_group"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List members of a group (members only) */
        get: operations["list_members"];
        put?: never;
        /** @description Add a user to a group (owner or group admin only) */
        post: operations["add_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Change a member's role (owner only; cannot assign owner role) */
        put: operations["set_member_role"];
        post?: never;
        /** @description Remove a member or leave a group (owner/admin for others; any member for self) */
        delete: operations["remove_member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all registered users (server admin only) */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List proposals submitted by the authenticated user */
        get: operations["list_my_proposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List waterways with optional filters and pagination */
        get: operations["list_waterways"];
        put?: never;
        /** @description Create a waterway (admin: immediate 201, others: proposal 202) */
        post: operations["create_waterway"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a waterway with its sections */
        get: operations["get_waterway"];
        /** @description Update a waterway (admin: immediate 200, others: proposal 202) */
        put: operations["update_waterway"];
        post?: never;
        /** @description Delete a waterway (admin: immediate 204, others: proposal 202) */
        delete: operations["delete_waterway"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a section (admin: immediate 201, others: proposal 202) */
        post: operations["create_section"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a section with its features */
        get: operations["get_section"];
        /** @description Update a section (admin: immediate 200, others: proposal 202) */
        put: operations["update_section"];
        post?: never;
        /** @description Delete a section (admin: immediate 204, others: proposal 202) */
        delete: operations["delete_section"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add a feature (admin: immediate 201, others: proposal 202) */
        post: operations["create_feature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a feature (admin: immediate 200, others: proposal 202) */
        put: operations["update_feature"];
        post?: never;
        /** @description Delete a feature (admin: immediate 204, others: proposal 202) */
        delete: operations["delete_feature"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/features/{feature_id}/names/{lang_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add or update a localized name for a feature */
        post: operations["upsert_feature_name"];
        /** @description Delete a localized name for a feature */
        delete: operations["delete_feature_name"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/features/{feature_id}/descriptions/{lang_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add or update a localized description for a feature */
        post: operations["upsert_feature_description"];
        /** @description Delete a localized description for a feature */
        delete: operations["delete_feature_description"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List comments on a section */
        get: operations["list_section_comments"];
        put?: never;
        /** @description Add a comment to a section */
        post: operations["create_section_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a section comment (author only) */
        put: operations["update_section_comment"];
        post?: never;
        /** @description Delete a section comment (author or admin) */
        delete: operations["delete_section_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/features/{feature_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List comments on a feature */
        get: operations["list_feature_comments"];
        put?: never;
        /** @description Add a comment to a feature */
        post: operations["create_feature_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/sections/{section_id}/features/{feature_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Update a feature comment (author only) */
        put: operations["update_feature_comment"];
        post?: never;
        /** @description Delete a feature comment (author or admin) */
        delete: operations["delete_feature_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List pending waterway and section proposals (admin only) */
        get: operations["list_waterway_proposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a waterway or section proposal (admin or submitter) */
        get: operations["get_waterway_proposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Approve or reject a waterway/section proposal (admin only) */
        patch: operations["review_waterway_proposal"];
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/features/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List feature proposals for a waterway (admin only) */
        get: operations["list_feature_proposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/waterways/{waterway_id}/features/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a feature proposal scoped to a waterway (admin or submitter) */
        get: operations["get_feature_proposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Approve or reject a feature proposal (admin only) */
        patch: operations["review_feature_proposal"];
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description plain text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain; charset=utf-8": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMemberBody: {
            /** @default member */
            role: components["schemas"]["GroupMemberRole"];
            user_id: string;
        };
        ApiToken: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: int64 */
            id: number;
            is_active: boolean;
            /** Format: date-time */
            last_used_at?: string | null;
            name: string;
            user_id: string;
        };
        ApiTokenCreated: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            /** @description The plain token - only shown once at creation time! */
            token: string;
        };
        Comment: {
            author_id: string;
            body: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            entity_id: number;
            entity_type: components["schemas"]["CommentEntityType"];
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        CommentEntityType: "water_section" | "feature";
        CreateCommentRequest: {
            body: string;
        };
        CreateFeatureBody: {
            feature_type: components["schemas"]["FeatureType"];
            location: components["schemas"]["Geometry"];
            /** @default {} */
            metadata: unknown;
        };
        CreateGroupBody: {
            description?: string | null;
            name: string;
        };
        CreateSectionBody: {
            description?: string | null;
            country?: string | null;
            location: components["schemas"]["Geometry"];
            name: string;
            region?: string | null;
        };
        CreateTokenBody: {
            /** Format: int64 */
            expires_in_days?: number | null;
            name: string;
        };
        CreateWaterwayBody: {
            description?: string | null;
            name: string;
        };
        Feature: {
            /** Format: date-time */
            created_at: string;
            created_by: string;
            descriptions: components["schemas"]["FeatureDescription"][];
            feature_type: components["schemas"]["FeatureType"];
            /** Format: int64 */
            id: number;
            /** @description GeoJSON geometry (Point, LineString, or Polygon) */
            location: components["schemas"]["Geometry"];
            metadata: unknown;
            names: components["schemas"]["FeatureName"][];
            /** Format: int64 */
            section_id: number;
            /** Format: date-time */
            updated_at: string;
        };
        FeatureCommentPath: {
            /** Format: int64 */
            comment_id: number;
            /** Format: int64 */
            feature_id: number;
            /** Format: int64 */
            section_id: number;
            /** Format: int64 */
            waterway_id: number;
        };
        FeatureDescription: {
            description: string;
            /** Format: int64 */
            feature_id: number;
            /** Format: int64 */
            id: number;
            lang_code: string;
        };
        FeatureLocalePath: {
            /** Format: int64 */
            feature_id: number;
            lang_code: string;
            /** Format: int64 */
            section_id: number;
            /** Format: int64 */
            waterway_id: number;
        };
        FeatureName: {
            /** Format: int64 */
            feature_id: number;
            /** Format: int64 */
            id: number;
            lang_code: string;
            name: string;
        };
        FeaturePath: {
            /** Format: int64 */
            feature_id: number;
            /** Format: int64 */
            section_id: number;
            /** Format: int64 */
            waterway_id: number;
        };
        FeatureProposalPath: {
            /** Format: int64 */
            proposal_id: number;
            /** Format: int64 */
            waterway_id: number;
        };
        /** @enum {string} */
        FeatureType: "whitewater" | "freestyle_spot" | "hole" | "siphon" | "weir" | "dam" | "obstacle" | "bridge" | "portage" | "put_in" | "take_out" | "waterfall";
        /** @description GeoJSON geometry object (RFC 7946) */
        Geometry: {
            /** @constant */
            type: "Point";
            coordinates: number[];
        } | {
            /** @constant */
            type: "LineString";
            coordinates: number[][];
        } | {
            /** @constant */
            type: "Polygon";
            coordinates: number[][][];
        } | {
            /** @constant */
            type: "MultiPoint";
            coordinates: number[][];
        } | {
            /** @constant */
            type: "MultiLineString";
            coordinates: number[][][];
        } | {
            /** @constant */
            type: "MultiPolygon";
            coordinates: number[][][][];
        };
        Group: {
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            created_by: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        GroupMember: {
            added_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            group_id: number;
            role: components["schemas"]["GroupMemberRole"];
            user_id: string;
            username: string;
        };
        /** @enum {string} */
        GroupMemberRole: "owner" | "admin" | "member";
        GroupWithMembers: {
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            created_by: string;
            /** Format: int64 */
            id: number;
            members: components["schemas"]["GroupMember"][];
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        ListFeatureProposalsQuery: {
            status?: string | null;
        };
        ListProposalsQuery: {
            entity_type?: string | null;
            status?: string | null;
        };
        PaginatedResponse_for_Waterway: {
            items: components["schemas"]["Waterway"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            per_page: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            total_pages: number;
        };
        Proposal: {
            /** Format: date-time */
            created_at: string;
            /**
             * Format: int64
             * @description ID of the existing record for update/delete operations; null for create
             */
            entity_id?: number | null;
            entity_type: components["schemas"]["ProposalEntityType"];
            /** Format: int64 */
            id: number;
            operation: components["schemas"]["ProposalOperation"];
            /** @description Full snapshot of the proposed state */
            proposed_data: unknown;
            review_note?: string | null;
            reviewed_by?: string | null;
            status: components["schemas"]["ProposalStatus"];
            submitted_by: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        ProposalEntityType: "waterway" | "water_section" | "feature";
        /** @enum {string} */
        ProposalOperation: "create" | "update" | "delete";
        ProposalPath: {
            /** Format: int64 */
            proposal_id: number;
        };
        /** @enum {string} */
        ProposalStatus: "pending" | "approved" | "rejected";
        /** @description Request body for approving or rejecting a proposal */
        ReviewRequest: {
            review_note?: string | null;
            status: components["schemas"]["ProposalStatus"];
        };
        RevokeTokenPath: {
            /** Format: int64 */
            token_id: number;
        };
        Section: {
            description?: string | null;
            country?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            /** @description GeoJSON LineString geometry */
            location: components["schemas"]["Geometry"];
            name: string;
            region?: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            waterway_id: number;
        };
        SectionCommentPath: {
            /** Format: int64 */
            comment_id: number;
            /** Format: int64 */
            section_id: number;
            /** Format: int64 */
            waterway_id: number;
        };
        SectionPath: {
            /** Format: int64 */
            section_id: number;
            /** Format: int64 */
            waterway_id: number;
        };
        SectionWithFeatures: {
            description?: string | null;
            country?: string | null;
            /** Format: date-time */
            created_at: string;
            features: components["schemas"]["Feature"][];
            /** Format: int64 */
            id: number;
            /** @description GeoJSON LineString geometry */
            location: components["schemas"]["Geometry"];
            name: string;
            region?: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            waterway_id: number;
        };
        SetRoleBody: {
            role: components["schemas"]["GroupMemberRole"];
        };
        UpdateCommentRequest: {
            body: string;
        };
        UpdateFeatureBody: {
            feature_type?: components["schemas"]["FeatureType"] | null;
            location?: components["schemas"]["Geometry"] | null;
            metadata?: unknown;
        };
        UpdateGroupBody: {
            /** @description Pass null to clear the description, omit to leave it unchanged */
            description?: string | null;
            name?: string | null;
        };
        UpdateSectionBody: {
            description?: string | null;
            country?: string | null;
            location?: components["schemas"]["Geometry"] | null;
            name?: string | null;
            region?: string | null;
        };
        UpdateWaterwayBody: {
            description?: string | null;
            name?: string | null;
        };
        UpsertDescriptionBody: {
            description: string;
        };
        UpsertNameBody: {
            name: string;
        };
        User: {
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            updated_at: string;
            username: string;
        };
        Waterway: {
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: date-time */
            updated_at: string;
            waterway_type: components["schemas"]["WaterwayType"];
        };
        WaterwayFilters: {
            /** @description Filter by ISO 3166-1 alpha-2 country code (e.g. "AT", "FR"). */
            country?: string | null;
            /**
             * Format: double
             * @description Latitude for proximity filter (requires lon and radius_km).
             */
            lat?: number | null;
            /**
             * Format: double
             * @description Longitude for proximity filter (requires lat and radius_km).
             */
            lon?: number | null;
            /**
             * Format: int32
             * @description Maximum whitewater grade (1=I … 6=VI, 10=X).
             */
            max_difficulty?: number | null;
            /**
             * Format: int32
             * @description Minimum whitewater grade (1=I … 6=VI, 10=X).
             */
            min_difficulty?: number | null;
            /** @description Filter by river name (case-insensitive substring match). */
            name?: string | null;
            /**
             * Format: int64
             * @description Page number, starting at 1.
             */
            page?: number | null;
            /**
             * Format: int64
             * @description Items per page (max 100, default 20).
             */
            per_page?: number | null;
            /**
             * Format: double
             * @description Radius in km — returns waterways with at least one section within this distance.
             */
            radius_km?: number | null;
        };
        WaterwayPath: {
            /** Format: int64 */
            waterway_id: number;
        };
        /** @enum {string} */
        WaterwayType: "river";
        WaterwayWithSections: {
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            sections: components["schemas"]["Section"][];
            /** Format: date-time */
            updated_at: string;
            waterway_type: components["schemas"]["WaterwayType"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "created_at": "2026-05-10T09:39:07.759927310Z",
                     *         "expires_at": "2026-08-08T09:39:07.759929330Z",
                     *         "id": 1,
                     *         "is_active": true,
                     *         "last_used_at": "2026-05-10T09:39:07.759934040Z",
                     *         "name": "CI/CD Pipeline",
                     *         "user_id": "user-uuid"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["ApiToken"][];
                };
            };
        };
    };
    create_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "created_at": "2026-05-10T09:39:07.760080330Z",
                     *       "expires_at": "2026-08-08T09:39:07.760080660Z",
                     *       "id": 1,
                     *       "name": "CI/CD Pipeline",
                     *       "token": "pm_a1b2c3d4e5f6..."
                     *     }
                     */
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
            /** @description Token with this name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token not found or already revoked */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_groups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupBody"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithMembers"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_members: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    add_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberBody"];
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Group or user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_member_role: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_member: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_my_proposals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_waterways: {
        parameters: {
            query?: {
                /** @description Filter by ISO 3166-1 alpha-2 country code (e.g. "AT", "FR"). */
                country?: string | null;
                /** @description Latitude for proximity filter (requires lon and radius_km). */
                lat?: number | null;
                /** @description Longitude for proximity filter (requires lat and radius_km). */
                lon?: number | null;
                /** @description Maximum whitewater grade (1=I … 6=VI, 10=X). */
                max_difficulty?: number | null;
                /** @description Minimum whitewater grade (1=I … 6=VI, 10=X). */
                min_difficulty?: number | null;
                /** @description Filter by river name (case-insensitive substring match). */
                name?: string | null;
                /** @description Page number, starting at 1. */
                page?: number | null;
                /** @description Items per page (max 100, default 20). */
                per_page?: number | null;
                /** @description Radius in km — returns waterways with at least one section within this distance. */
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_for_Waterway"];
                };
            };
        };
    };
    create_waterway: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWaterwayBody"];
            };
        };
        responses: {
            /** @description Waterway created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Waterway"];
                };
            };
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_waterway: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterwayWithSections"];
                };
            };
            /** @description Waterway not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_waterway: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWaterwayBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Waterway"];
                };
            };
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Waterway not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_waterway: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Waterway not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_section: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSectionBody"];
            };
        };
        responses: {
            /** @description Section created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_section: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionWithFeatures"];
                };
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_section: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSectionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_section: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_feature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeatureBody"];
            };
        };
        responses: {
            /** @description Feature created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Section not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_feature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeatureBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feature"];
                };
            };
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Feature not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_feature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal submitted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Feature not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsert_feature_name: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                lang_code: string;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertNameBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureName"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Feature not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_feature_name: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                lang_code: string;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Name not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsert_feature_description: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                lang_code: string;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertDescriptionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureDescription"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Feature not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_feature_description: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                lang_code: string;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Description not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_section_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    create_section_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_section_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found or not your comment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_section_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_feature_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    create_feature_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_feature_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                feature_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found or not your comment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_feature_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                feature_id: number;
                section_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Comment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_waterway_proposals: {
        parameters: {
            query?: {
                entity_type?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_waterway_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_waterway_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        /** @description Request body for approving or rejecting a proposal */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Proposal not found or already reviewed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_feature_proposals: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_feature_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    review_feature_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
                waterway_id: number;
            };
            cookie?: never;
        };
        /** @description Request body for approving or rejecting a proposal */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Proposal not found or already reviewed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
