/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ProposalsIndexRouteImport } from './routes/proposals/index'
import { Route as WaterwaysSuggestSectionRouteImport } from './routes/waterways/suggest-section'
import { Route as WaterwaysWaterwayIdRouteImport } from './routes/waterways/$waterwayId'
import { Route as TripsNewRouteImport } from './routes/trips/new'
import { Route as TripsTripIdRouteImport } from './routes/trips/$tripId'
import { Route as ToolsGaugeCatalogRouteImport } from './routes/tools/gauge-catalog'
import { Route as ProposalsProposalIdRouteImport } from './routes/proposals/$proposalId'
import { Route as LogsNewRouteImport } from './routes/logs/new'
import { Route as LogsDescentIdRouteImport } from './routes/logs/$descentId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminProposalsIndexRouteImport } from './routes/admin/proposals/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterwaysSuggestSectionRoute = WaterwaysSuggestSectionRouteImport.update({
  id: '/waterways/suggest-section',
  path: '/waterways/suggest-section',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterwaysWaterwayIdRoute = WaterwaysWaterwayIdRouteImport.update({
  id: '/waterways/$waterwayId',
  path: '/waterways/$waterwayId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGaugeCatalogRoute = ToolsGaugeCatalogRouteImport.update({
  id: '/tools/gauge-catalog',
  path: '/tools/gauge-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsProposalIdRoute = ProposalsProposalIdRouteImport.update({
  id: '/proposals/$proposalId',
  path: '/proposals/$proposalId',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsNewRoute = LogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LogsRoute,
} as any)
const LogsDescentIdRoute = LogsDescentIdRouteImport.update({
  id: '/$descentId',
  path: '/$descentId',
  getParentRoute: () => LogsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProposalsIndexRoute = AdminProposalsIndexRouteImport.update({
  id: '/admin/proposals/',
  path: '/admin/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/logs/$descentId': typeof LogsDescentIdRoute
  '/logs/new': typeof LogsNewRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/tools/gauge-catalog': typeof ToolsGaugeCatalogRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/waterways/$waterwayId': typeof WaterwaysWaterwayIdRoute
  '/waterways/suggest-section': typeof WaterwaysSuggestSectionRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/admin/proposals/': typeof AdminProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/logs/$descentId': typeof LogsDescentIdRoute
  '/logs/new': typeof LogsNewRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/tools/gauge-catalog': typeof ToolsGaugeCatalogRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/waterways/$waterwayId': typeof WaterwaysWaterwayIdRoute
  '/waterways/suggest-section': typeof WaterwaysSuggestSectionRoute
  '/proposals': typeof ProposalsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/trips': typeof TripsIndexRoute
  '/admin/proposals': typeof AdminProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/logs/$descentId': typeof LogsDescentIdRoute
  '/logs/new': typeof LogsNewRoute
  '/proposals/$proposalId': typeof ProposalsProposalIdRoute
  '/tools/gauge-catalog': typeof ToolsGaugeCatalogRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/waterways/$waterwayId': typeof WaterwaysWaterwayIdRoute
  '/waterways/suggest-section': typeof WaterwaysSuggestSectionRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/admin/proposals/': typeof AdminProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/settings'
    | '/auth/callback'
    | '/logs/$descentId'
    | '/logs/new'
    | '/proposals/$proposalId'
    | '/tools/gauge-catalog'
    | '/trips/$tripId'
    | '/trips/new'
    | '/waterways/$waterwayId'
    | '/waterways/suggest-section'
    | '/proposals/'
    | '/tools/'
    | '/trips/'
    | '/admin/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/settings'
    | '/auth/callback'
    | '/logs/$descentId'
    | '/logs/new'
    | '/proposals/$proposalId'
    | '/tools/gauge-catalog'
    | '/trips/$tripId'
    | '/trips/new'
    | '/waterways/$waterwayId'
    | '/waterways/suggest-section'
    | '/proposals'
    | '/tools'
    | '/trips'
    | '/admin/proposals'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/settings'
    | '/auth/callback'
    | '/logs/$descentId'
    | '/logs/new'
    | '/proposals/$proposalId'
    | '/tools/gauge-catalog'
    | '/trips/$tripId'
    | '/trips/new'
    | '/waterways/$waterwayId'
    | '/waterways/suggest-section'
    | '/proposals/'
    | '/tools/'
    | '/trips/'
    | '/admin/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProposalsProposalIdRoute: typeof ProposalsProposalIdRoute
  ToolsGaugeCatalogRoute: typeof ToolsGaugeCatalogRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsNewRoute: typeof TripsNewRoute
  WaterwaysWaterwayIdRoute: typeof WaterwaysWaterwayIdRoute
  WaterwaysSuggestSectionRoute: typeof WaterwaysSuggestSectionRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  AdminProposalsIndexRoute: typeof AdminProposalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waterways/suggest-section': {
      id: '/waterways/suggest-section'
      path: '/waterways/suggest-section'
      fullPath: '/waterways/suggest-section'
      preLoaderRoute: typeof WaterwaysSuggestSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waterways/$waterwayId': {
      id: '/waterways/$waterwayId'
      path: '/waterways/$waterwayId'
      fullPath: '/waterways/$waterwayId'
      preLoaderRoute: typeof WaterwaysWaterwayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/gauge-catalog': {
      id: '/tools/gauge-catalog'
      path: '/tools/gauge-catalog'
      fullPath: '/tools/gauge-catalog'
      preLoaderRoute: typeof ToolsGaugeCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/$proposalId': {
      id: '/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof ProposalsProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/new': {
      id: '/logs/new'
      path: '/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof LogsNewRouteImport
      parentRoute: typeof LogsRoute
    }
    '/logs/$descentId': {
      id: '/logs/$descentId'
      path: '/$descentId'
      fullPath: '/logs/$descentId'
      preLoaderRoute: typeof LogsDescentIdRouteImport
      parentRoute: typeof LogsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proposals/': {
      id: '/admin/proposals/'
      path: '/admin/proposals'
      fullPath: '/admin/proposals/'
      preLoaderRoute: typeof AdminProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LogsRouteChildren {
  LogsDescentIdRoute: typeof LogsDescentIdRoute
  LogsNewRoute: typeof LogsNewRoute
}

const LogsRouteChildren: LogsRouteChildren = {
  LogsDescentIdRoute: LogsDescentIdRoute,
  LogsNewRoute: LogsNewRoute,
}

const LogsRouteWithChildren = LogsRoute._addFileChildren(LogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProposalsProposalIdRoute: ProposalsProposalIdRoute,
  ToolsGaugeCatalogRoute: ToolsGaugeCatalogRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  TripsNewRoute: TripsNewRoute,
  WaterwaysWaterwayIdRoute: WaterwaysWaterwayIdRoute,
  WaterwaysSuggestSectionRoute: WaterwaysSuggestSectionRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  AdminProposalsIndexRoute: AdminProposalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
