/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalsIndexRouteImport } from './routes/proposals/index'
import { Route as WaterwaysWaterwayIdRouteImport } from './routes/waterways/$waterwayId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminProposalsIndexRouteImport } from './routes/admin/proposals/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsIndexRoute = ProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterwaysWaterwayIdRoute = WaterwaysWaterwayIdRouteImport.update({
  id: '/waterways/$waterwayId',
  path: '/waterways/$waterwayId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProposalsIndexRoute = AdminProposalsIndexRouteImport.update({
  id: '/admin/proposals/',
  path: '/admin/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/waterways/$waterwayId': typeof WaterwaysWaterwayIdRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/admin/proposals/': typeof AdminProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/waterways/$waterwayId': typeof WaterwaysWaterwayIdRoute
  '/proposals': typeof ProposalsIndexRoute
  '/admin/proposals': typeof AdminProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/waterways/$waterwayId': typeof WaterwaysWaterwayIdRoute
  '/proposals/': typeof ProposalsIndexRoute
  '/admin/proposals/': typeof AdminProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/settings'
    | '/auth/callback'
    | '/waterways/$waterwayId'
    | '/proposals/'
    | '/admin/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/settings'
    | '/auth/callback'
    | '/waterways/$waterwayId'
    | '/proposals'
    | '/admin/proposals'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/settings'
    | '/auth/callback'
    | '/waterways/$waterwayId'
    | '/proposals/'
    | '/admin/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  WaterwaysWaterwayIdRoute: typeof WaterwaysWaterwayIdRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
  AdminProposalsIndexRoute: typeof AdminProposalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof ProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waterways/$waterwayId': {
      id: '/waterways/$waterwayId'
      path: '/waterways/$waterwayId'
      fullPath: '/waterways/$waterwayId'
      preLoaderRoute: typeof WaterwaysWaterwayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proposals/': {
      id: '/admin/proposals/'
      path: '/admin/proposals'
      fullPath: '/admin/proposals/'
      preLoaderRoute: typeof AdminProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  WaterwaysWaterwayIdRoute: WaterwaysWaterwayIdRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
  AdminProposalsIndexRoute: AdminProposalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
